- name: Extend Filesystem
  hosts: all
  become: true
  vars_files:
    - ../vars/fsextendvar.yaml

  tasks:
    - name: Extend the Logical Volume
      command: lvextend -L {{ desired_size_gb }}G /dev/{{ vg_name }}/{{ lv_name }}
      changed_when: false

    - name: Resize the Filesystem
      command: xfs_growfs {{ mount_point }}

